FROM hyperf/hyperf:8.3-alpine-v3.19-swoole

# 安装 PostgreSQL 开发包和 pdo_pgsql 扩展
RUN apk add --no-cache postgresql-dev \
    && docker-php-ext-install pdo_pgsql \
    && apk del postgresql-dev \
    && rm -rf /var/cache/apk/*

# 设置时区
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone

# 设置工作目录
WORKDIR /www

# 暴露端口
EXPOSE 9501 9503